/**
 * Directory helpers.
 *
 * MOCK_MODE=true  → synthetic ACME Corp data (lib/mockData.js)
 * MOCK_MODE=false → real Swisscom data (lib/neliData.json, generated by getNeliInfo.ts)
 *
 * LDAP has been removed; no external network calls are made by this module.
 */
import { existsSync, readFileSync } from 'fs'
import { join } from 'path'
import NodeCache from 'node-cache'
import { mockTree as _mockTree, mockUsers as _mockUsers, findMockUserByCredentials } from './mockData.js'
import type { OrgNode, User, AuthUser } from '@/types'

const MOCK_MODE = process.env.MOCK_MODE === 'true'
const CACHE_TTL = Number(process.env.CACHE_TTL ?? 300)
const cache = new NodeCache({ stdTTL: CACHE_TTL, checkperiod: 60 })

// ─── Neli data (loaded once on first use when MOCK_MODE=false) ────────────────

interface NeliData {
  users: User[]
  tree:  OrgNode
  skills: Record<string, string[]> | null
}

let _neliData: NeliData | null = null

function getNeliData(): NeliData {
  if (_neliData) return _neliData
  const p = join(process.cwd(), 'lib', 'neliData.json')
  if (!existsSync(p)) {
    throw new Error(
      'MOCK_MODE is not "true" but lib/neliData.json does not exist. ' +
      'Run: npx ts-node getNeliInfo.ts "Bearer <token>" <userId>',
    )
  }
  _neliData = JSON.parse(readFileSync(p, 'utf-8')) as NeliData
  return _neliData
}

// ─── User normaliser ─────────────────────────────────────────────────────────
// Converts raw ACME mock objects (sAMAccountName etc.) into User shape.
// Neli data is already in User shape so this is essentially a pass-through.

function normaliseUser(raw: any): User {
  const photo = raw.photo ?? raw.thumbnailPhoto
  return {
    dn:         raw.dn         ?? '',
    cn:         raw.cn         ?? '',
    username:   raw.username   ?? raw.sAMAccountName ?? '',
    mail:       raw.mail       ?? '',
    title:      raw.title      ?? '',
    department: (raw.department ?? '').trim(),
    phone:      raw.phone      ?? raw.telephoneNumber ?? '',
    mobile:     raw.mobile     ?? '',
    office:     raw.office     ?? raw.physicalDeliveryOfficeName ?? '',
    city:       raw.city       ?? raw.l ?? '',
    country:    (raw.country   ?? raw.c ?? '').trim(),
    company:    raw.company    ?? '',
    manager:    raw.manager    ?? '',
    photo:      typeof photo === 'string' && photo.length < 200000 ? photo : null,
  }
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function ldapGetTree(): Promise<OrgNode> {
  const cached = cache.get<OrgNode>('tree')
  if (cached) return cached

  const tree = MOCK_MODE ? (_mockTree as unknown as OrgNode) : getNeliData().tree
  cache.set('tree', tree)
  return tree
}

export async function ldapGetUsers(baseDN: string): Promise<User[]> {
  const cacheKey = `users:${baseDN.toLowerCase()}`
  const cached   = cache.get<User[]>(cacheKey)
  if (cached) return cached

  let users: User[]

  if (MOCK_MODE) {
    const seen     = new Set<string>()
    let   filterDn = baseDN.toLowerCase()
    const mockRoot = 'dc=acme,dc=com'
    if (!filterDn.endsWith(mockRoot)) filterDn = mockRoot

    users = (_mockUsers as any[])
      .filter((u) => {
        const dn = u.dn.toLowerCase()
        if (!(dn === filterDn || dn.endsWith(',' + filterDn))) return false
        if (seen.has(dn)) return false
        seen.add(dn)
        return true
      })
      .map(normaliseUser)
  } else {
    const allUsers = getNeliData().users
    const seen     = new Set<string>()

    const isDN = baseDN.includes('=')
    users = (
      baseDN && !isDN
        ? allUsers.filter((u) => {
            const dept = u.department ?? ''
            return dept === baseDN || dept.startsWith(baseDN + '-')
          })
        : allUsers
    ).filter((u) => {
      if (seen.has(u.dn)) return false
      seen.add(u.dn)
      return true
    })
  }

  cache.set(cacheKey, users)
  return users
}

/**
 * Returns a skills map from lib/neliData.json (non-mock mode only).
 * Returns null in mock mode — callers should fall back to mockSkillsStore.
 */
export function getNeliSkills(): Map<string, string[]> | null {
  if (MOCK_MODE) return null
  const { skills } = getNeliData()
  if (!skills) return new Map()
  const map = new Map<string, string[]>()
  for (const [dn, list] of Object.entries(skills)) {
    const expanded = (list as string[]).flatMap((s) =>
      s.split(';').map((p) => p.trim()).filter(Boolean)
    )
    map.set(dn, expanded)
  }
  return map
}

export async function ldapBindUser(username: string, password: string): Promise<AuthUser | null> {
  // No real bind — accept password "mock" against the active dataset
  if (password !== 'mock') return null

  let raw: any
  if (MOCK_MODE) {
    raw = (findMockUserByCredentials as any)(username, null)
  } else {
    const { users } = getNeliData()
    raw = users.find((u) => u.username?.toLowerCase() === username.toLowerCase()) ?? null
  }

  if (!raw) return null
  const u = normaliseUser(raw)
  return { dn: u.dn, cn: u.cn, username: u.username, mail: u.mail,
           title: u.title, department: u.department,
           phone: u.phone, mobile: u.mobile, office: u.office }
}

export async function ldapResolveUser(username: string, mail: string): Promise<AuthUser | null> {
  const users: any[] = MOCK_MODE ? (_mockUsers as any[]) : getNeliData().users

  let match = username
    ? users.find((u) =>
        (u.username ?? u.sAMAccountName ?? '').toLowerCase() === username.toLowerCase()
      )
    : null

  if (!match && mail) {
    match = users.find((u) => (u.mail ?? '').toLowerCase() === mail.toLowerCase()) ?? null
  }

  if (!match) return null
  const u = normaliseUser(match)
  return { dn: u.dn, cn: u.cn, username: u.username, mail: u.mail,
           title: u.title, department: u.department,
           phone: u.phone, mobile: u.mobile, office: u.office }
}
